### ISSUE TITLE
Album attributes not present in Track.

### ISSUE THREAD

**Issue by aandis** [timcase/echowrap#13]
Echowrap.song_search(
        :title => "Born to Die", 
        :artist => "Lana Del Rey", 
        :song_type => "studio",
        :bucket => ['tracks', 'id:7digital-US'],
        :limit => true).first

results in

`#<Echowrap::Song:0x007f3b829a6a90 @attrs={:title=>"Born To Die", :artist_name=>"Lana Del Rey", :artist_foreign_ids=>[{:catalog=>"7digital-US", :foreign_id=>"7digital-US:artist:1107056"}], :tracks=>[{:album_type=>"unknown", :release_image=>"http://artwork-cdn.7static.com/static/img/sleeveart/00/015/712/0001571223_200.jpg", :album_date=>"2012-01-27", :foreign_release_id=>"7digital-US:release:1571223", :preview_url=>"http://previews.7digital.com/clip/17296574", :catalog=>"7digital-US", :foreign_id=>"7digital-US:track:17296574", :album_name=>"Born to Die", :id=>"TREKOIE135C7E8E556"}], :artist_id=>"ARICLSK131AAE25F5E", :id=>"SOJJEAF144BDB4FA1B"}>`

Accessing `result.tracks.first.album_name` throws error.

**Comment by timcase** [comment]
This is now added in version 0.2.0
